export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

export const CREATE_MOVIES_SUCCESS = "CREATE_MOVIES_SUCCESS";
export const CREATE_MOVIES_FAIL = "CREATE_MOVIES_FAIL";

export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_FAIL = "GET_MOVIES_FAIL";

export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS";
export const GET_MOVIE_FAIL = "GET_MOVIE_FAIL";

export const GET_RANDOM_MOVIE_SUCCESS = "GET_RANDOM_MOVIE_SUCCESS";
export const GET_RANDOM_MOVIE_FAIL = "GET_RANDOM_MOVIE_FAIL";

export const UPDATE_MOVIE_SUCCESS = "UPDATE_MOVIE_SUCCESS";
export const UPDATE_MOVIE_FAIL = "UPDATE_MOVIE_FAIL";

export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";
export const DELETE_MOVIE_FAIL = "DELETE_MOVIE_FAIL";

export const CREATE_LIST_SUCCESS = "CREATE_LIST_SUCCESS";
export const CREATE_LIST_FAIL = "CREATE_LIST_FAIL";

export const GET_LISTS_SUCCESS = "GET_LISTS_SUCCESS";
export const GET_LISTS_FAIL = "GET_LISTS_FAIL";

export const DELETE_LIST_SUCCESS = "DELETE_LIST_SUCCESS";
export const DELETE_LIST_FAIL = "DELETE_LIST_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";
export const CLEAR_SUCCESS = "CLEAR_SUCCESS";

export const SET_REGISTER_LOADING = "SET_REGISTER_LOADING";
export const SET_LOADING_USER = "SET_LOADING_USER";
export const SET_LOADING_MOVIE = "SET_LOADING_MOVIE";
export const SET_LOADING_LIST = "SET_LOADING_LIST";
