export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const CLEART_ERROR = "CLEAR_ERROR";
export const CLEART_SUCCESS = "CLEAR_SUCCESS";

export const SET_REGISTER_LOADING = "SET_REGISTER_LOADING";
